site_name: Отчеты по лабораторным работам. Малышев Сергей, K3339

theme:
  name: windmill
  language: ru
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.top

nav:
  - 'Главная': 'index.md'
  - 'Лабораторная работа №1':
    - 'Задание 1: UDP Клиент-Сервер': 'lr_1/task1.md'
    - 'Задание 2: TCP Калькулятор': 'lr_1/task2.md'
    - 'Задание 3: HTTP Сервер': 'lr_1/task3.md'
    - 'Задание 4: TCP Чат': 'lr_1/task4.md'
    - 'Задание 5: Веб-сервер (GET/POST)': 'lr_1/task5.md'
  - 'Лабораторная работа №2': 'lr_2/lr_2.md'